# Generated by Django 3.0 on 2020-11-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=25)),
                ('period', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='city',
        ),
    ]
