# Generated by Django 3.1.3 on 2020-11-16 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapi', '0002_auto_20201116_1510'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Period',
        ),
        migrations.AlterModelOptions(
            name='weather',
            options={'verbose_name_plural': 'weather'},
        ),
    ]
